/**
 * A message moving through the queue. `body` is a `string` so callers own their own
 * encoding (JSON, base64, …) and the queue stays a dumb transport — the same divergence
 * from typed payloads the rest of the platform makes to keep providers portable.
 */
export interface Message {
  /** Unique identifier; auto-generated by {@link Publisher.publish} when absent. */
  id: string;
  /** The opaque payload. Callers encode/decode their own structure. */
  body: string;
  /** Optional string-keyed metadata carried alongside the body. */
  attributes?: Record<string, string>;
}

/** A message handed to {@link Publisher.publish}; the `id` is filled in when omitted. */
export type OutgoingMessage = Omit<Message, "id"> & { id?: string };

/** Invoked for each message delivered to a subscription. Errors propagate to the caller. */
export type MessageHandler = (message: Message) => Promise<void>;

/** Publishes messages to a topic. */
export interface Publisher {
  /** Publishes a message to `topic`, generating an `id` when one is not supplied. */
  publish(topic: string, message: OutgoingMessage): Promise<void>;
  /** Verifies the backing broker is reachable. */
  ping(): Promise<void>;
}

/** A live subscription that can be torn down. */
export interface Subscription {
  /** Stops delivery to this subscription's handler. Idempotent. */
  unsubscribe(): Promise<void>;
}

/** Subscribes handlers to topics. */
export interface Consumer {
  /** Registers `handler` to receive messages published to `topic`. */
  subscribe(topic: string, handler: MessageHandler): Promise<Subscription>;
  /** Verifies the backing broker is reachable. */
  ping(): Promise<void>;
}

/**
 * The message-queue contract: a combined {@link Publisher} and {@link Consumer}. Providers
 * implement this single interface so call-site code is identical across backends.
 */
export interface MessageQueue extends Publisher, Consumer {}
